"""Squashed initial schema for SIH26100.

ponytail: single clean revision created by squashing the inherited SIH26034
migration history. DDL is generated from the current models metadata instead
of hand-written create_table calls — correct for a fresh database and keeps
this file from drifting out of sync with models.py during the sprint.
Upgrade path: switch to hand-written/autogenerated revisions once the schema
stops being recreated between demo iterations.
"""
import os
import sys

from alembic import op

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from app.db.models import Base  # noqa: E402

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
